# Introcução a Numpy

[Numpy](https://numpy.org/) é a biblioteca central para computação científica em Python. Ele fornece um objeto de matriz multidimensional de alto desempenho e ferramentas para trabalhar com essas matrizes.

Para iniciarmos, importaremos a biblioteca numpy e a chamaremos por np ao longo dos códigos. Caso não tenha o numpy instalado, você pode facilmente instalá-lo utilizando o pip (``pip install numpy``)

In [1]:
import numpy as np

## Arrays

Uma matriz em numpy é uma matriz de valores do mesmo tipo (chamado de ``dtype``). O número de dimensões de uma matriz é chamada de *rank*. A forma de uma matriz (*shape*) é uma tupla de inteiros fornecendo o tamanho da matriz ao longo de cada dimensão. 

As matrizes podem ser inicializadas de diversas formas:
* Através de listas ou listas aninhadas, utilizando a funçao ``array``

* Matrizes de zeros ou uns, com as funções ``zeros`` ou ``ones``

* Com números aleatórios, com a função ``random.random``

* Sem nenhum elemento, com a função ``empty``

* Uma matriz identidade, com a função ``eye``

* Uma matriz com elementos constantes, com a função ``full``

* Com intervalos, com a função ``arange``

* Entre outros

In [8]:
a = [1.2, 2.2, 3.2]
b = [[10, 20,30], [40, 50, 60]]

x = np.array(a)
print(x)
print("---------")

y = np.array(b)
print(y)
print("---------")

print(f"Forma de x: {x.shape}. Tipo dos elementos: {x.dtype}")
print(f"Forma de y: {y.shape}. Tipo dos elementos: {y.dtype}")

[1.2 2.2 3.2]
---------
[[10 20 30]
 [40 50 60]]
---------
Forma de x: (3,). Tipo dos elementos: float64
Forma de y: (2, 3). Tipo dos elementos: int64


In [11]:
x = np.zeros((2,2))
print(x)
print(f"Forma de x: {x.shape}. Tipo dos elementos: {x.dtype}")
print("---------")

y = np.ones((2,2,2))
print(y)
print(f"Forma de y: {y.shape}. Tipo dos elementos: {y.dtype}")
print("---------")

z = np.random.random((3,3))
print(z)
print(f"Forma de z: {z.shape}. Tipo dos elementos: {z.dtype}")
print("---------")

[[0. 0.]
 [0. 0.]]
Forma de x: (2, 2). Tipo dos elementos: float64
---------
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
Forma de y: (2, 2, 2). Tipo dos elementos: float64
---------
[[0.86092934 0.20699571 0.30553429]
 [0.92945455 0.99882481 0.88809106]
 [0.51864817 0.64228192 0.88091856]]
Forma de z: (3, 3). Tipo dos elementos: float64
---------


In [14]:
x = np.eye(4)
print(x)
print(f"Forma de x: {x.shape}. Tipo dos elementos: {x.dtype}")
print("---------")

y = np.full((2,2), 3.14)
print(y)
print(f"Forma de y: {y.shape}. Tipo dos elementos: {y.dtype}")
print("---------")

z = np.arange(10)
print(z)
print(f"Forma de z: {z.shape}. Tipo dos elementos: {z.dtype}")
print("---------")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Forma de x: (4, 4). Tipo dos elementos: float64
---------
[[3.14 3.14]
 [3.14 3.14]]
Forma de y: (2, 2). Tipo dos elementos: float64
---------
[0 1 2 3 4 5 6 7 8 9]
Forma de z: (10,). Tipo dos elementos: int64
---------


## Indexação de Matrizes

Uma matriz pode ser [indexada de diversas formas](https://numpy.org/doc/stable/user/quickstart.html#quickstart-indexing-slicing-and-iterating), por uma tupla de inteiros não-negativos, por expressões booleanas, por outra matriz ou por inteiros. 

**Fatias**: Semelhante às listas Python, arrays entorpecidos podem ser fatiados. Como as matrizes podem ser multidimensionais, você deve especificar uma fatia para cada dimensão da matriz.

In [16]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
print("----------")

y = x[:2, 1:3]
print(y) 
print("----------")

y[0, 0] = 77 
print(x[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------
[[2 3]
 [6 7]]
----------
77
